version: 0.2

phases:
  pre_build:
    commands:
      - echo Install NPM
      - npm install
  build:
    commands:
      - echo Build iniciado em `date`
      - echo   -> Build WebSite
      - npm run build
  post_build:
    commands:
      - echo Build finalizado em `date`

artifacts:
  files:
    - build/**/*
    - Scripts/**/*
    - Config/AppSpec.yml